data:
  name: MNIST
  path: data
  url: gdrive://1zQqlTQ2qcfPGL1gbe05-Ttr7r-EXhUhH
model:
  name: mnist_cnn
  n_classes: 10
training:
  batch_size: 64
  epochs: 5
  lr: 0.1
  gamma: 0.7
  seed: 1
  save_model: True
  accelerator: gpu
